### ISSUE TITLE
NMIND checklist

### ISSUE THREAD

**Issue by Remi-Gau** [bids-apps/giga_connectome#44]
Putting it here as some sort "roadmap".
adapted from https://www.nmind.org/standards-checklist/

This can also help determine what is an achievable "scope goal" / milestone before publication

Maybe we can discuss in this issues things that are:
- already done
- to do
- won't do (before publication)

For the TODOs, we can create separate issues and tick them off in here once they are done.

# NMIND bronze certif

## testing

- [x] Provide / generate / point to test data
- [x] Provide instructions for users to run tests that include instructions for evaluation for correct behavior

## infrastructure

- [x] Code is open source
- [x] Package is under version control
- [x] Readme is present
- [x] License is present
- [x] Issues tracking is enabled
- [ ] Digital Object Identifier (DOI) points to latest version
- [x] All documented installation instructions can be successfully followed

## documentation

- [x] Landing page (e.g., GitHub README, website) provides a link to documentation and brief description of what program does
- [x] Documentation is up to date with version of software
- [x] Typical intended usage is described
- [x] An example of its usage is shown
- [x] Document functions intended to be used by users.
      **Only intended to be used as container so only the CLI matters**.
- [x] Description of required input parameters for user-facing functions with reasonable description of inputs
- [x] Description of output(s)
- [x] User installation instructions available
- [x] Dependencies listed

# NMIND silver certif

## testing

- [x] Some form of testing suite present
- [x] Test coverage > 50%

## infrastructure

- [ ] Issue template(s) available
- [x] Continuous integration runs tests
- [x] No excessive files included

## documentation

- [ ] Background/significance of program
- [ ] One or more tutorial to showcase the multiple of the program's usages
- [x] Any alternative usage that is advertised is thoroughly documented
- [x] Thorough description of required and optional input parameters
- [x] Document public functions
- [ ] A statement of supported operating systems / environments

# NMIND gold certif

## testing

- [x] Test coverage > 90%
- [ ] Benchmarking information is provided for examples

## infrastructure

- [ ] Continuous integration builds packages
- [x] Continuous integration validates style
- [ ] Journal of Open Source Software submission
- [x] Contribution guide present
- [x] Code of Conduct present

## documentation

- [ ] Continuous integration badges in README for build status
- [x] Continuous integration badges in README for tests passing
- [x] Continuous integration badges in README for coverage
- [ ] Document functions, classes, modules, etc.
- [ ] Has a documented style guide
- [ ] Maintenance status is documented

# JOSS "checklist"

- The software must be open source as per the [OSI definition](https://opensource.org/osd).
-    The software must be hosted at a location where users can open issues and propose code changes without manual approval of (or payment for) accounts.
-    The software must have an obvious research application.
-    You must be a major contributor to the software you are submitting, and have a GitHub account to participate in the review process.
-    Your paper must not focus on new research results accomplished with the software.
-    Your paper (paper.md and BibTeX files, plus any figures) must be hosted in a Git-based repository together with your software (although they may be in a short-lived branch which is never merged with the default).

In addition, the software associated with your submission must:

-    Be stored in a repository that can be cloned without registration.
-    Be stored in a repository that is browsable online without registration.
-    Have an issue tracker that is readable without registration.
-    Permit individuals to create issues/file tickets against your repository.

**Comment by htwangtw** [comment]
This is great! When I was evaluating the JOSS submission, I also thought about what is worth the effort based on the scale of the project etc., and the set up of this project more or less reflects on some of the choices I made. This is going to be very useful for future reference as well

**Comment by Remi-Gau** [comment]
We could have the JOSS checklist right below the one for NMIND. Can help roadmapping.

**Comment by Remi-Gau** [comment]
Possibly want to run this checklist too:

https://learn.scientific-python.org/development/guides/repo-review/

Also exist as a package: https://repo-review.readthedocs.io/

**Comment by htwangtw** [comment]
> Possibly want to run this checklist too:
> 
> https://learn.scientific-python.org/development/guides/repo-review/
> 
> Also exist as a package: https://repo-review.readthedocs.io/

Brah it didn't find my tests directory when there's no way that I will leave it out

When do you aim to run through all the items? Anything I can do?

**Comment by Remi-Gau** [comment]
> Brah it didn't find my tests directory when there's no way that I will leave it out

I think it needs to be defined in the pytest section

> When do you aim to run through all the items? Anything I can do?

Give me the green light and I will start getting to work.

**Comment by htwangtw** [comment]
@Remi-Gau It's ready to go - start the reviews!

**Comment by Remi-Gau** [comment]
> @Remi-Gau It's ready to go - start the reviews!

Cracks knuckles.

"let's get his party started".

**Comment by Remi-Gau** [comment]
@htwangtw 

going through some of the points in the list and am wondering if the goal to distribute the app as both a python package AND a container image or only as a container?

**Comment by htwangtw** [comment]
I wish to distribute it only as a container

**Comment by htwangtw** [comment]
We can close this as a lot of the points only apply to really large projects
